/**
 * Official GGG Currency Exchange API (Faustus market data).
 *
 * Endpoint: https://web.poecdn.com/api/currency-exchange/{unixHour}
 * Public, no auth. Returns completed-hour digests only (the current hour 404s,
 * so data lags ~1-2h behind live). Per market pair it reports both sides'
 * traded volume, the lowest/highest executed ratio within the hour (real
 * buy/sell gap) and lowest/highest stock (real order-book depth).
 *
 * This module fuses that with poe.ninja (live ~5 min prices, names, icons):
 * item ids are GGG metadata paths, mapped to names via the committed
 * cxNames.json (regenerated by scripts/cx-names.mjs in the snapshot CI).
 */

import cxNames from "@/data/poe/cxNames.json";
import { CX_TYPES, getFlipBoard, type OfficialPairInfo } from "./ninja";

const CX_BASE = "https://web.poecdn.com/api/currency-exchange";
const USER_AGENT = process.env.APP_USER_AGENT ?? "FastBuildPOE/0.1 (+https://fastbuildpoe.xyz)";
const CHAOS_ID = "Metadata/Items/Currency/CurrencyRerollRare";
const DIVINE_ID = "Metadata/Items/Currency/CurrencyModValues";
const DIGEST_TTL_MS = 3 * 60 * 60 * 1000;
const LATEST_HOUR_TTL_MS = 2 * 60 * 1000;
const MAX_WALK_BACK_HOURS = 5;

interface OfficialMarket {
  league: string;
  market_id: string;
  market_pair: [string, string];
  volume_traded: Record<string, number>;
  lowest_stock: Record<string, number>;
  highest_stock: Record<string, number>;
  lowest_ratio: Record<string, number>;
  highest_ratio: Record<string, number>;
}

interface Digest {
  next_change_id: number;
  markets?: OfficialMarket[];
}

const digestCache = new Map<number, { value: Digest | null; expires: number }>();
let latestHourCache: { id: number; expires: number } | null = null;

async function fetchDigest(hourId: number): Promise<Digest | null> {
  const hit = digestCache.get(hourId);
  if (hit && hit.expires > Date.now()) return hit.value;
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 10000);
    let res: Response;
    try {
      res = await fetch(`${CX_BASE}/${hourId}`, {
        headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
        cache: "no-store",
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timer);
    }
    if (!res.ok) {
      // 404 = hour not published yet (or pruned); cache the miss briefly.
      digestCache.set(hourId, { value: null, expires: Date.now() + LATEST_HOUR_TTL_MS });
      return null;
    }
    const json = (await res.json()) as Digest;
    digestCache.set(hourId, { value: json, expires: Date.now() + DIGEST_TTL_MS });
    return json;
  } catch {
    return null;
  }
}

/** Newest fully-published hour (start timestamp), walking back from now. */
async function resolveLatestHour(): Promise<number | null> {
  if (latestHourCache && latestHourCache.expires > Date.now()) return latestHourCache.id;
  const currentHour = Math.floor(Date.now() / 1000 / 3600) * 3600;
  for (let k = 1; k <= MAX_WALK_BACK_HOURS; k++) {
    const hourId = currentHour - k * 3600;
    const digest = await fetchDigest(hourId);
    if (digest && (digest.markets?.length ?? 0) > 0) {
      latestHourCache = { id: hourId, expires: Date.now() + LATEST_HOUR_TTL_MS };
      return hourId;
    }
  }
  return null;
}

const NAMES = cxNames as Record<string, string>;
const norm = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]/g, "");

/** "AncestralOmenOnFusingMakeFullLinks" → "Ancestral Omen On Fusing Make Full Links" */
function prettyId(id: string): string {
  const segment = id.split("/").pop() ?? id;
  return segment.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/([A-Za-z])(\d)/g, "$1 $2");
}

const nameOf = (id: string): string => NAMES[id] ?? prettyId(id);

interface RatioBounds {
  /** Quote units per 1 base unit — lowest and highest executed in the hour. */
  lo: number | null;
  hi: number | null;
  gapPct: number | null;
}

function ratioBounds(market: OfficialMarket, baseId: string, quoteId: string): RatioBounds {
  const reads: number[] = [];
  for (const dict of [market.lowest_ratio, market.highest_ratio]) {
    const base = dict[baseId] ?? 0;
    const quote = dict[quoteId] ?? 0;
    if (base > 0 && quote > 0) reads.push(quote / base);
  }
  if (reads.length === 0) return { lo: null, hi: null, gapPct: null };
  const lo = Math.min(...reads);
  const hi = Math.max(...reads);
  return { lo, hi, gapPct: lo > 0 ? ((hi - lo) / lo) * 100 : null };
}

export interface PairRow {
  id: string;
  baseId: string;
  quoteId: string;
  baseName: string;
  quoteName: string;
  baseIcon: string | null;
  /** Quote units per 1 base — executed range within the hour. */
  rateLo: number | null;
  rateHi: number | null;
  /** (rateHi − rateLo) / rateLo — the intra-hour buy/sell gap. */
  gapPct: number | null;
  volBase: number;
  volQuote: number;
  /** Traded volume converted to chaos where possible. */
  volumeChaos: number | null;
  /** Peak order-book stock during the hour, per side. */
  stockBase: number;
  stockQuote: number;
  /** Live poe.ninja chaos price of the base item, for context. */
  liveChaos: number | null;
}

export interface PairBoard {
  league: string;
  hourStart: number;
  hourEnd: number;
  divinePrice: number | null;
  rows: PairRow[];
  fetchedAt: number;
}

interface NinjaIndexEntry {
  icon: string | null;
  chaosRate: number;
}

async function ninjaNameIndex(
  league: string,
): Promise<{ byName: Map<string, NinjaIndexEntry>; divinePrice: number | null }> {
  const boards = await Promise.all(CX_TYPES.map((t) => getFlipBoard(league, t)));
  const byName = new Map<string, NinjaIndexEntry>();
  let divinePrice: number | null = null;
  for (const board of boards) {
    if (!board) continue;
    divinePrice = divinePrice ?? board.divinePrice;
    for (const row of board.rows) {
      const key = norm(row.name);
      if (!byName.has(key)) byName.set(key, { icon: row.image, chaosRate: row.chaosRate });
    }
  }
  return { byName, divinePrice };
}

function marketsOf(digest: Digest, league: string): OfficialMarket[] {
  const wanted = league.toLowerCase();
  const exact = (digest.markets ?? []).filter((m) => m.league.toLowerCase() === wanted);
  if (exact.length > 0) return exact;
  // League ids can differ slightly between poe.ninja and the official feed at
  // a league launch — fall back to a containment match before giving up.
  return (digest.markets ?? []).filter((m) => {
    const have = m.league.toLowerCase();
    return have.includes(wanted) || wanted.includes(have);
  });
}

/** Full pair table for the newest published hour. */
export async function getPairBoard(league: string): Promise<PairBoard | null> {
  const [hourId, ninja] = await Promise.all([resolveLatestHour(), ninjaNameIndex(league)]);
  if (hourId === null) return null;
  const digest = await fetchDigest(hourId);
  if (!digest) return null;

  const rows: PairRow[] = [];
  for (const market of marketsOf(digest, league)) {
    const [a, b] = market.market_pair;
    const totalVol = (market.volume_traded[a] ?? 0) + (market.volume_traded[b] ?? 0);
    if (totalVol <= 0) continue;

    const aNinja = ninja.byName.get(norm(nameOf(a)));
    const bNinja = ninja.byName.get(norm(nameOf(b)));
    // Quote priority: divine > chaos > the pricier side (per live ninja rates).
    let quoteId: string;
    if (a === DIVINE_ID || b === DIVINE_ID) quoteId = a === DIVINE_ID ? a : b;
    else if (a === CHAOS_ID || b === CHAOS_ID) quoteId = a === CHAOS_ID ? a : b;
    else quoteId = (aNinja?.chaosRate ?? 0) >= (bNinja?.chaosRate ?? 0) ? a : b;
    const baseId = quoteId === a ? b : a;
    const baseNinja = baseId === a ? aNinja : bNinja;
    const quoteNinja = quoteId === a ? aNinja : bNinja;

    const bounds = ratioBounds(market, baseId, quoteId);
    const volQuote = market.volume_traded[quoteId] ?? 0;
    const volBase = market.volume_traded[baseId] ?? 0;
    let volumeChaos: number | null = null;
    if (quoteId === CHAOS_ID) volumeChaos = volQuote;
    else if (quoteId === DIVINE_ID && ninja.divinePrice) volumeChaos = volQuote * ninja.divinePrice;
    else if (quoteNinja) volumeChaos = volQuote * quoteNinja.chaosRate;
    else if (baseNinja) volumeChaos = volBase * baseNinja.chaosRate;

    rows.push({
      id: market.market_id,
      baseId,
      quoteId,
      baseName: nameOf(baseId),
      quoteName: nameOf(quoteId),
      baseIcon: baseNinja?.icon ?? null,
      rateLo: bounds.lo,
      rateHi: bounds.hi,
      gapPct: bounds.gapPct,
      volBase,
      volQuote,
      volumeChaos,
      stockBase: market.highest_stock[baseId] ?? 0,
      stockQuote: market.highest_stock[quoteId] ?? 0,
      liveChaos: baseNinja?.chaosRate ?? null,
    });
  }
  rows.sort((x, y) => (y.volumeChaos ?? -1) - (x.volumeChaos ?? -1));

  return {
    league,
    hourStart: hourId,
    hourEnd: hourId + 3600,
    divinePrice: ninja.divinePrice,
    rows,
    fetchedAt: Date.now(),
  };
}

export interface ItemPairIndex {
  hourStart: number;
  hourEnd: number;
  byName: Map<string, OfficialPairInfo>;
}

/**
 * Per-item official stats vs chaos and vs divine, for enriching the live
 * poe.ninja flip board (joined by item name).
 */
export async function getItemPairIndex(league: string): Promise<ItemPairIndex | null> {
  const hourId = await resolveLatestHour();
  if (hourId === null) return null;
  const digest = await fetchDigest(hourId);
  if (!digest) return null;

  const byName = new Map<string, OfficialPairInfo>();
  const entryFor = (itemId: string): OfficialPairInfo => {
    const key = norm(nameOf(itemId));
    const existing = byName.get(key);
    if (existing) return existing;
    const fresh: OfficialPairInfo = {
      chaosGapPct: null,
      divineGapPct: null,
      depthItems: null,
      volumeChaos1h: null,
      volumeDiv1h: null,
      chaosMid: null,
      divineMid: null,
    };
    byName.set(key, fresh);
    return fresh;
  };

  for (const market of marketsOf(digest, league)) {
    const [a, b] = market.market_pair;
    const isChaos = a === CHAOS_ID || b === CHAOS_ID;
    const isDivine = a === DIVINE_ID || b === DIVINE_ID;
    if (!isChaos && !isDivine) continue;
    const quoteId = isChaos ? (a === CHAOS_ID ? a : b) : a === DIVINE_ID ? a : b;
    const itemId = quoteId === a ? b : a;
    if (itemId === CHAOS_ID || itemId === DIVINE_ID) continue;

    const bounds = ratioBounds(market, itemId, quoteId);
    const entry = entryFor(itemId);
    const stock = market.highest_stock[itemId] ?? 0;
    entry.depthItems = Math.max(entry.depthItems ?? 0, stock);
    const mid =
      bounds.lo !== null && bounds.hi !== null ? Math.sqrt(bounds.lo * bounds.hi) : null;
    if (isChaos) {
      entry.chaosGapPct = bounds.gapPct;
      entry.chaosMid = mid;
      entry.volumeChaos1h = (entry.volumeChaos1h ?? 0) + (market.volume_traded[quoteId] ?? 0);
    } else {
      entry.divineGapPct = bounds.gapPct;
      entry.divineMid = mid;
      entry.volumeDiv1h = (entry.volumeDiv1h ?? 0) + (market.volume_traded[quoteId] ?? 0);
    }
  }

  return { hourStart: hourId, hourEnd: hourId + 3600, byName };
}

export const normalizeName = norm;
