import type { ItemSetView, ParsedItem } from "@/types/item";

/**
 * The price table this app writes into a build's PoB Notes, and the matching
 * reader that takes it back out.
 *
 * Client-safe on purpose: `encode.ts` needs the stripper but pulls in
 * `node:zlib`, so the shared pieces live here where the export button can
 * import them too.
 */

/**
 * Human-facing title and a visually hidden end marker. PoB's Notes understand
 * `^xRRGGBB` colours; black keeps the machine marker out of the way on its dark
 * editor while leaving a stable delimiter for the next export.
 */
export const PRICE_BLOCK_HEADER = "^xFF9922PRICE BREAKDOWN^7";
export const PRICE_BLOCK_FOOTER = "^x000000[fbp:end]^7";

/** Blocks written before the compact, colour-coded layout. */
const LEGACY_PRICE_BLOCKS: Array<[string, string]> = [
  ["=== FastBuildPOE — Price Check ===", "(generated by fastbuildpoe.xyz)"],
];

const DEFAULT = "^7";
const CURRENCY = "^xAA9E82";
const POSITIVE = "^x33FF77";
const HIDDEN = "^x000000";

const GROUP_COLOR: Record<string, string> = {
  Gear: "^xFFFF77",
  Jewels: "^xB54BFF",
  Gems: "^x1AA29B",
  Flasks: "^x88FFFF",
  Charms: "^x5CF0BB",
};

const RARITY_COLOR: Record<ParsedItem["rarity"], string> = {
  normal: "^xC8C8C8",
  magic: "^x8888FF",
  rare: "^xFFFF77",
  unique: "^xAF6025",
  gem: "^x1AA29B",
  currency: CURRENCY,
};

/**
 * Machine-readable copy of the prices, written inside the block so a shared
 * paste can restore the exact price inputs — the table above it is for humans
 * and is lossy (it prints no gem level or quality, and skips unpriced items).
 *
 * Base64url only, so it needs no XML escaping and survives the Notes round trip
 * untouched. Living inside the block means `stripPriceBlocks` clears it along
 * with everything else on the next export.
 */
const DATA_OPEN = "[fbp:";
const DATA_LINE = /\[fbp:([A-Za-z0-9_-]+)\]/;

/** Pull the encoded price payload out of a build's Notes, if it carries one. */
export function extractPriceData(notes: string): string | null {
  return notes.match(DATA_LINE)?.[1] ?? null;
}

/** Round a divine amount the way the UI does: no trailing .0, else one decimal. */
function formatDivine(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}

/**
 * Remove every price table a previous export left behind.
 *
 * Export re-resolves the build from its original input, so a build that was
 * already exported once (or imported back from an exported pobb.in link) still
 * carries the old table — appending gave the user a second one stacked under
 * the first, with the stale prices on top. Stripping first makes export
 * idempotent: the notes always end with exactly one, current, table.
 */
export function stripPriceBlocks(notes: string): string {
  let out = notes;
  for (const [header, footer] of [
    [PRICE_BLOCK_HEADER, PRICE_BLOCK_FOOTER] as [string, string],
    ...LEGACY_PRICE_BLOCKS,
  ]) {
    const segments = out.split(header);
    let kept = segments[0];
    for (const segment of segments.slice(1)) {
      const end = segment.indexOf(footer);
      // A block with no footer was truncated — it runs to the end of the notes.
      kept += end === -1 ? "" : segment.slice(end + footer.length);
    }
    out = kept;
  }
  return out.replace(/\n{3,}/g, "\n\n").trim();
}

/**
 * Render the current view's prices as the block PoB will show in Notes.
 *
 * `data` is the encoded price payload from `encodeEmbeddedPrices`. Passed when
 * the paste is going to back a share link and has to be readable again; omitted
 * for a plain export, which only needs the human table.
 */
export function buildPriceNotes(
  view: ItemSetView,
  getPrice: (key: string) => string,
  keyFor: (item: ParsedItem) => string,
  sumItems: (items: ParsedItem[]) => number,
  data?: string,
): string {
  const lines: string[] = [];
  const allGems = view.gems.flatMap((g) => g.gems);
  const groups: Array<[string, ParsedItem[]]> = [
    ["Gear", view.gear],
    ["Jewels", view.jewels],
    ["Gems", allGems],
    ["Flasks", view.flasks],
    ["Charms", view.charms],
  ];

  for (const [label, items] of groups) {
    const priced = items.filter((it) => {
      const value = Number.parseFloat(getPrice(keyFor(it)) || "");
      return Number.isFinite(value) && value > 0;
    });
    if (priced.length === 0) continue;
    lines.push(
      `${GROUP_COLOR[label] ?? DEFAULT}${label.toUpperCase()}${DEFAULT}` +
      `  ${CURRENCY}${formatDivine(sumItems(items))} div${DEFAULT}`,
    );
    for (const it of priced) {
      const price = getPrice(keyFor(it));
      // Unique and gem names already identify the item; repeating their base
      // adds noise. Rare/magic names need the base to remain recognisable.
      const showBase =
        (it.rarity === "rare" || it.rarity === "magic") &&
        it.baseType &&
        it.baseType !== it.name;
      const name = showBase ? `${it.name} (${it.baseType})` : it.name;
      const slot = it.slot ? `${it.slot} · ` : "";
      lines.push(
        `  ${DEFAULT}${slot}${RARITY_COLOR[it.rarity]}${name}${DEFAULT}` +
        ` — ${CURRENCY}${price} div${DEFAULT}`,
      );
    }
  }

  const total = sumItems([...view.gear, ...view.jewels, ...allGems, ...view.flasks, ...view.charms]);
  const header = `${PRICE_BLOCK_HEADER}\n${POSITIVE}TOTAL  ${formatDivine(total)} div${DEFAULT}`;
  const encoded = data ? `\n${HIDDEN}${DATA_OPEN}${data}]${DEFAULT}` : "";
  return `${header}\n\n${lines.join("\n")}\n${encoded}\n${PRICE_BLOCK_FOOTER}`;
}
