import type { ItemSetView, ParsedItem } from "@/types/item";

/**
 * The price table this app writes into a build's PoB Notes, and the matching
 * reader that takes it back out.
 *
 * Client-safe on purpose: `encode.ts` needs the stripper but pulls in
 * `node:zlib`, so the shared pieces live here where the export button can
 * import them too.
 */

/** Delimiters of a generated block. Stable — older exports are found by them. */
export const PRICE_BLOCK_HEADER = "=== FastBuildPOE — Price Check ===";
export const PRICE_BLOCK_FOOTER = "(generated by fastbuildpoe.xyz)";

/**
 * Machine-readable copy of the prices, written inside the block so a shared
 * paste can restore the exact price inputs — the table above it is for humans
 * and is lossy (it prints no gem level or quality, and skips unpriced items).
 *
 * Base64url only, so it needs no XML escaping and survives the Notes round trip
 * untouched. Living inside the block means `stripPriceBlocks` clears it along
 * with everything else on the next export.
 */
const DATA_OPEN = "[fbp:";
const DATA_LINE = /\[fbp:([A-Za-z0-9_-]+)\]/;

/** Pull the encoded price payload out of a build's Notes, if it carries one. */
export function extractPriceData(notes: string): string | null {
  return notes.match(DATA_LINE)?.[1] ?? null;
}

/** Round a divine amount the way the UI does: no trailing .0, else one decimal. */
function formatDivine(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}

/**
 * Remove every price table a previous export left behind.
 *
 * Export re-resolves the build from its original input, so a build that was
 * already exported once (or imported back from an exported pobb.in link) still
 * carries the old table — appending gave the user a second one stacked under
 * the first, with the stale prices on top. Stripping first makes export
 * idempotent: the notes always end with exactly one, current, table.
 */
export function stripPriceBlocks(notes: string): string {
  const segments = notes.split(PRICE_BLOCK_HEADER);
  let out = segments[0];
  for (const segment of segments.slice(1)) {
    const end = segment.indexOf(PRICE_BLOCK_FOOTER);
    // A block with no footer was truncated — it runs to the end of the notes.
    out += end === -1 ? "" : segment.slice(end + PRICE_BLOCK_FOOTER.length);
  }
  return out.replace(/\n{3,}/g, "\n\n").trim();
}

/**
 * Render the current view's prices as the block PoB will show in Notes.
 *
 * `data` is the encoded price payload from `encodeEmbeddedPrices`. Passed when
 * the paste is going to back a share link and has to be readable again; omitted
 * for a plain export, which only needs the human table.
 */
export function buildPriceNotes(
  view: ItemSetView,
  getPrice: (key: string) => string,
  keyFor: (item: ParsedItem) => string,
  sumItems: (items: ParsedItem[]) => number,
  data?: string,
): string {
  const lines: string[] = [];
  const allGems = view.gems.flatMap((g) => g.gems);
  const groups: Array<[string, ParsedItem[]]> = [
    ["Gear", view.gear],
    ["Jewels", view.jewels],
    ["Gems", allGems],
    ["Flasks", view.flasks],
    ["Charms", view.charms],
  ];

  for (const [label, items] of groups) {
    const priced = items.filter((it) => {
      const value = Number.parseFloat(getPrice(keyFor(it)) || "");
      return Number.isFinite(value) && value > 0;
    });
    if (priced.length === 0) continue;
    lines.push(`[${label}] ${formatDivine(sumItems(items))} div`);
    for (const it of priced) {
      const price = getPrice(keyFor(it));
      const name = it.baseType && it.baseType !== it.name ? `${it.name} (${it.baseType})` : it.name;
      const slot = it.slot ? `${it.slot} — ` : "";
      lines.push(`  ${slot}${name}: ${price} div`);
    }
  }

  const total = sumItems([...view.gear, ...view.jewels, ...allGems, ...view.flasks, ...view.charms]);
  const header = `${PRICE_BLOCK_HEADER}\nTotal: ${formatDivine(total)} div\n`;
  const encoded = data ? `${DATA_OPEN}${data}]\n` : "";
  return `${header}\n${lines.join("\n")}\n\n${encoded}${PRICE_BLOCK_FOOTER}`;
}
